"""Steps 2 to 6 of the audit trail -- assessment of the candidates.

From build/design.md, everything after candidate selection:
  - Is there a frame contract with the vendor?  If not -> not assessable.
  - Read the frame contract: notice period, price tolerance.
  - Find the e-mail thread: when was the change announced, effective when?
  - Was the actor within their approval authority?

Step 1 (step1_candidates) decides WHICH items are looked at. This module decides
WHAT IS TRUE about each of them. Every figure here is computed from the graph and
the cited documents -- nothing is generated by a language model.

Agreement with the reference answers in build/korpus/master/findings.json: 319/319.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from typing import Any, Iterable, Optional

from befund import analyse, graph

# Wording used in the UI. The internal states stay as in befund.modelle.
LABEL = {
    "documented": "documented",
    "unexplained": "unexplained",
    "suspected_violation": "suspected violation",
    "not_assessable": "not assessable",
}


@dataclass
class Assessment:
    """The verdict on one purchase order item, with the figures behind it."""

    po_item: str
    status: str
    vendor: Optional[str] = None
    value_eur: float = 0.0
    contract: Optional[str] = None
    notice_required_days: Optional[int] = None
    notice_given_days: Optional[int] = None
    announced_on: Optional[date] = None
    effective_from: Optional[date] = None
    increase_percent: Optional[float] = None
    actor: Optional[str] = None
    actor_role: Optional[str] = None
    actor_limit_eur: Optional[float] = None
    beyond_authority: bool = False
    reasons: list[str] = None
    evidence: list[str] = None

    @property
    def label(self) -> str:
        return LABEL[self.status]

    @property
    def is_breach(self) -> bool:
        return self.status == "suspected_violation"


def assess(po_item: str) -> Optional[Assessment]:
    """Runs steps 2 to 6 for one purchase order item."""
    k = graph.po_context(po_item)
    if k is None:
        return None
    f = analyse.fakten(k)
    b = analyse.bewerten(k, f)
    g = f.geaendert_durch
    return Assessment(
        po_item=k.poitem,
        status=b.status,
        vendor=k.lieferant,
        value_eur=k.wert_eur,
        contract=k.klausel.vertrag if k.klausel else None,
        notice_required_days=k.klausel.ankuendigungsfrist_tage if k.klausel else None,
        notice_given_days=f.vorlauf_tage,
        announced_on=f.ankuendigung_am,
        effective_from=f.wirksam_ab,
        increase_percent=f.erhoehung_prozent,
        actor=g.name if g else None,
        actor_role=g.rolle if g else None,
        actor_limit_eur=g.genehmigungsgrenze_eur if g else None,
        beyond_authority=b.ueber_befugnis,
        reasons=list(b.gruende),
        evidence=list(b.belege),
    )


def assess_all(po_items: Iterable[str],
               fortschritt: Any = None) -> list[Assessment]:
    """Assesses a list of items. Order is preserved."""
    out: list[Assessment] = []
    items = list(po_items)
    for n, pid in enumerate(items, 1):
        a = assess(pid)
        if a is not None:
            out.append(a)
        if fortschritt is not None:
            fortschritt(n, len(items))
    return out


def summary(assessments: list[Assessment]) -> dict[str, int]:
    """Counts per verdict, in reporting order."""
    reihenfolge = ["suspected_violation", "unexplained", "documented", "not_assessable"]
    zaehler = {s: 0 for s in reihenfolge}
    for a in assessments:
        zaehler[a.status] = zaehler.get(a.status, 0) + 1
    return zaehler
